const caregiverData = [
  {
    id: 1,
    name: "Mary Johnson",
    patientName: "John Johnson",
    relationship: "Spouse",
    email: "mary.j@example.com",
    phone: "+1 234-567-8901",
    address: "123 Family St, Care City",
    status: "Active",
    accessLevel: "Full",
    joinDate: "2024-03-15",
    notes: "Primary caregiver",
  },
  {
    id: 2,
    name: "David Smith",
    patientName: "Emma Smith",
    relationship: "Father",
    email: "david.s@example.com",
    phone: "+1 987-654-3210",
    address: "456 Support Ave, Health Town",
    status: "Active",
    accessLevel: "Limited",
    joinDate: "2024-04-10",
    notes: "Emergency contact",
  },

  {
    id: 3,
    name: "Sarah Wilson",
    patientName: "Michael Wilson",
    relationship: "Daughter",
    email: "sarah.w@example.com",
    phone: "+1 555-789-1234",
    address: "789 Care Lane, Wellness City",
    status: "Pending",
    accessLevel: "Full",
    joinDate: "2024-05-20",
    notes: "Awaiting approval",
  },

  {
    id: 4,
    name: "Robert Brown",
    patientName: "Linda Brown",
    relationship: "Son",
    email: "robert.b@example.com",
    phone: "+1 444-567-8901",
    address: "321 Family Rd, Health Town",
    status: "Pending",
    accessLevel: "Limited",
    joinDate: "2024-06-01",
    notes: "Verification in progress",
  },

  {
    id: 5,
    name: "Emily Davis",
    patientName: "James Davis",
    relationship: "Sister",
    email: "emily.d@example.com",
    phone: "+1 333-456-7890",
    address: "654 Support St, Recovery City",
    status: "Suspended",
    accessLevel: "Full",
    joinDate: "2024-02-12",
    notes: "Access suspended",
  },

  {
    id: 6,
    name: "Thomas Miller",
    patientName: "Sophia Miller",
    relationship: "Brother",
    email: "thomas.m@example.com",
    phone: "+1 222-345-6789",
    address: "987 Wellness Ave, Care City",
    status: "Suspended",
    accessLevel: "Limited",
    joinDate: "2024-01-25",
    notes: "Account under review",
  },
];

export default caregiverData;